DROP TABLE customers CASCADE;
DROP TABLE shops CASCADE;
DROP TABLE books CASCADE;
DROP TABLE orders CASCADE;



CREATE TABLE customers (
	id SERIAL PRIMARY KEY,
	last_name TEXT NOT NULL,
	district TEXT NOT NULL,
	sale DOUBLE PRECISION NOT NULL
);

CREATE TABLE shops (
	id SERIAL NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	district TEXT NOT NULL,
	commission DOUBLE PRECISION NOT NULL
);

CREATE TABLE books (
	id SERIAL NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	price INTEGER NOT NULL,
	storage TEXT NOT NULL,
	count INTEGER NOT NULL
);

CREATE TABLE orders (
	id SERIAL NOT NULL PRIMARY KEY,
	date DATE NOT NULL,
	seller INTEGER NOT NULL REFERENCES shops(id),
	customer INTEGER NOT NULL REFERENCES customers(id),
	book INTEGER NOT NULL REFERENCES books(id) ,
	count INTEGER NOT NULL,
	cost INTEGER NOT NULL
);

